rootLogger.level=ERROR
appender.console.type=Console
appender.console.name=console
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{HH:mm:ss} %-5p %m%n
rootLogger.appenderRef.console.ref=console
